In [1]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.5)

In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import string
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [4]:
df = pd.read_csv('/content/blogs.csv')
df

                                                   Data              Labels
0     Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...         alt.atheism
1     Newsgroups: alt.atheism\nPath: cantaloupe.srv....         alt.atheism
2     Path: cantaloupe.srv.cs.cmu.edu!das-news.harva...         alt.atheism
3     Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...         alt.atheism
4     Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:53...         alt.atheism
...                                                 ...                 ...
1995  Xref: cantaloupe.srv.cs.cmu.edu talk.abortion:...  talk.religion.misc
1996  Xref: cantaloupe.srv.cs.cmu.edu talk.religion....  talk.religion.misc
1997  Xref: cantaloupe.srv.cs.cmu.edu talk.origins:4...  talk.religion.misc
1998  Xref: cantaloupe.srv.cs.cmu.edu talk.religion....  talk.religion.misc
1999  Xref: cantaloupe.srv.cs.cmu.edu sci.skeptic:43...  talk.religion.misc

[2000 rows x 2 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Data    2000 non-null   object
 1   Labels  2000 non-null   object
dtypes: object(2)
memory usage: 31.4+ KB

In [13]:
def convert_lower(text):
  return text.lower()
def tokenize(text):
  return nltk.word_tokenize(text)

In [14]:
stop_words = set(stopwords.words('english'))
def remove_stopwords(tokens):
  return[word for word in tokens if word not in stop_words]

In [15]:
df['processed_text'] = df['Data'].apply(convert_lower)
df['processed_text'] = df['processed_text'].apply(tokenize)
df['processed_text'] = df['processed_text'].apply(remove_stopwords)

In [16]:
df['processed_text'] = df['processed_text'].apply(lambda x:''.join(x))

In [22]:
tfidf = TfidfVectorizer()

In [23]:
tfidf_matrix = tfidf.fit_transform(df['processed_text'])

In [24]:
tfidf_df=pd.DataFrame(tfidf_matrix.toarray(),columns=tfidf.get_feature_names_out())

In [25]:
tfidf_df

       00  000  0000001200  000005102000  00000510200001user  ...  zz0  zz2q1  zzs  zztop  zzx
0     0.0  0.0         0.0           0.0                 0.0  ...  0.0    0.0  0.0    0.0  0.0
1     0.0  0.0         0.0           0.0                 0.0  ...  0.0    0.0  0.0    0.0  0.0
2     0.0  0.0         0.0           0.0                 0.0  ...  0.0    0.0  0.0    0.0  0.0
3     0.0  0.0         0.0           0.0                 0.0  ...  0.0    0.0  0.0    0.0  0.0
4     0.0  0.0         0.0           0.0                 0.0  ...  0.0    0.0  0.0    0.0  0.0
...   ...  ...         ...           ...                 ...  ...  ...    ...  ...    ...  ...
1995  0.0  0.0         0.0           0.0                 0.0  ...  0.0    0.0  0.0    0.0  0.0
1996  0.0  0.0         0.0           0.0                 0.0  ...  0.0    0.0  0.0    0.0  0.0
1997  0.0  0.0         0.0           0.0                 0.0  ...  0.0    0.0  0.0    0.0  0.0
1998  0.0  0.0         0.0           0.0                 0.0  ...  0.0    0.0  0.0    0.0  0.0
1999  0.0  0.0         0.0           0.0                 0.0  ...  0.0    0.0  0.0    0.0  0.0

[2000 rows x 100093 columns]

In [26]:
tfidf_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Columns: 100093 entries, 00 to zzx
dtypes: float64(100093)
memory usage: 1.5 GB

In [27]:
X = tfidf.fit_transform(df['processed_text'])
Y = df['Labels']

In [28]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report

In [30]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [32]:
nb = MultinomialNB()

In [33]:
nb.fit(x_train,y_train)

MultinomialNB()

In [34]:
y_pred = nb.predict(x_test)
y_pred

array(['talk.politics.mideast', 'comp.sys.ibm.pc.hardware', 'sci.med',
       'rec.sport.baseball', 'comp.sys.ibm.pc.hardware',
       'rec.sport.hockey', 'rec.sport.baseball', 'talk.politics.mideast',
       'alt.atheism', 'sci.med', 'alt.atheism',
       'comp.sys.ibm.pc.hardware', 'sci.crypt', 'rec.sport.baseball',
       'comp.sys.ibm.pc.hardware', 'comp.os.ms-windows.misc', 'rec.autos',
       'misc.forsale', 'talk.politics.guns', 'talk.politics.misc',
       'misc.forsale', 'talk.politics.misc', 'talk.religion.misc',
       'sci.electronics', 'alt.atheism', 'alt.atheism', 'sci.crypt',
       'rec.sport.baseball', 'rec.autos', 'alt.atheism', 'misc.forsale',
       'rec.sport.hockey', 'comp.os.ms-windows.misc', 'sci.electronics',
       'rec.sport.hockey', 'comp.sys.mac.hardware', 'sci.med',
       'rec.sport.hockey', 'rec.sport.hockey', 'comp.os.ms-windows.misc',
       'comp.sys.ibm.pc.hardware', 'talk.religion.misc',
       'comp.os.ms-windows.misc', 'comp.graphics',
       'soc.religion.christian', 'rec.motorcycles',
       'comp.os.ms-windows.misc', 'rec.motorcycles', 'alt.atheism',
       'talk.religion.misc', 'soc.religion.christian', 'sci.crypt',
       'sci.space', 'talk.politics.misc', 'rec.sport.baseball',
       'talk.politics.mideast', 'sci.electronics', 'talk.politics.guns',
       'sci.crypt', 'comp.graphics', 'sci.space', 'misc.forsale',
       'talk.politics.guns', 'rec.sport.hockey', 'talk.politics.misc',
       'talk.politics.misc', 'rec.sport.hockey', 'soc.religion.christian',
       'comp.graphics', 'sci.space', 'sci.space', 'misc.forsale',
       'sci.med', 'rec.sport.hockey', 'rec.autos',
       'comp.sys.ibm.pc.hardware', 'talk.politics.misc', 'rec.autos',
       'rec.sport.baseball', 'talk.politics.misc', 'alt.atheism',
       'rec.motorcycles', 'sci.space', 'soc.religion.christian',
       'talk.politics.misc', 'rec.sport.hockey', 'talk.politics.mideast',
       'sci.electronics', 'comp.os.ms-windows.misc', 'sci.crypt',
       'soc.religion.christian', 'talk.politics.mideast',
       'comp.os.ms-windows.misc', 'talk.politics.guns',
       'talk.politics.misc', 'talk.politics.misc',
       'comp.sys.mac.hardware', 'sci.med', 'soc.religion.christian',
       'talk.politics.misc', 'rec.sport.baseball', 'rec.motorcycles',
       'comp.sys.mac.hardware', 'sci.med', 'comp.os.ms-windows.misc',
       'comp.os.ms-windows.misc', 'rec.autos', 'comp.os.ms-windows.misc',
       'misc.forsale', 'sci.crypt', 'rec.motorcycles', 'misc.forsale',
       'rec.sport.hockey', 'talk.politics.mideast', 'rec.autos',
       'comp.sys.ibm.pc.hardware', 'sci.crypt', 'rec.sport.baseball',
       'alt.atheism', 'comp.sys.ibm.pc.hardware', 'talk.politics.misc',
       'rec.sport.hockey', 'sci.crypt', 'comp.sys.mac.hardware',
       'comp.sys.ibm.pc.hardware', 'soc.religion.christian',
       'rec.motorcycles', 'rec.motorcycles', 'sci.crypt',
       'comp.sys.ibm.pc.hardware', 'talk.religion.misc',
       'talk.politics.misc', 'rec.autos', 'comp.windows.x',
       'rec.motorcycles', 'comp.sys.ibm.pc.hardware', 'alt.atheism',
       'alt.atheism', 'talk.politics.guns', 'soc.religion.christian',
       'sci.med', 'comp.sys.ibm.pc.hardware', 'talk.politics.misc',
       'rec.motorcycles', 'soc.religion.christian', 'comp.windows.x',
       'misc.forsale', 'comp.sys.mac.hardware', 'comp.os.ms-windows.misc',
       'comp.graphics', 'talk.religion.misc', 'rec.motorcycles',
       'misc.forsale', 'sci.crypt', 'comp.sys.ibm.pc.hardware',
       'misc.forsale', 'rec.sport.baseball', 'talk.politics.guns',
       'comp.sys.ibm.pc.hardware', 'rec.motorcycles', 'misc.forsale',
       'talk.politics.guns', 'rec.autos', 'sci.crypt',
       'talk.religion.misc', 'sci.space', 'talk.politics.mideast',
       'sci.electronics', 'comp.os.ms-windows.misc',
       'talk.politics.mideast', 'sci.crypt', 'sci.med', 'alt.atheism',
       'talk.politics.misc', 'comp.sys.mac.hardware', 'sci.med',
       'sci.electronics', 'misc.forsale', 'rec.autos',
       'talk.politics.guns', 'sci.electronics', 'rec.autos',
       'talk.politics.misc', 'sci.crypt', 'rec.motorcycles', 'rec.autos',
       'alt.atheism', 'sci.electronics', 'sci.med', 'sci.electronics',
       'sci.electronics', 'comp.os.ms-windows.misc', 'sci.med',
       'comp.os.ms-windows.misc', 'talk.religion.misc',
       'comp.sys.mac.hardware', 'sci.crypt', 'rec.motorcycles',
       'misc.forsale', 'soc.religion.christian', 'rec.sport.hockey',
       'sci.electronics', 'comp.graphics', 'rec.autos', 'sci.crypt',
       'comp.os.ms-windows.misc', 'sci.space', 'rec.sport.baseball',
       'rec.sport.hockey', 'alt.atheism', 'talk.politics.mideast',
       'alt.atheism', 'comp.os.ms-windows.misc', 'sci.crypt', 'rec.autos',
       'talk.politics.misc', 'sci.crypt', 'comp.sys.ibm.pc.hardware',
       'comp.graphics', 'comp.graphics', 'rec.sport.baseball',
       'talk.politics.misc', 'comp.windows.x', 'sci.crypt',
       'soc.religion.christian', 'talk.religion.misc', 'comp.graphics',
       'rec.autos', 'talk.politics.misc', 'comp.sys.mac.hardware',
       'misc.forsale', 'comp.os.ms-windows.misc', 'talk.politics.guns',
       'comp.graphics', 'talk.politics.mideast',
       'comp.sys.ibm.pc.hardware', 'rec.sport.hockey', 'rec.motorcycles',
       'sci.med', 'comp.graphics', 'comp.sys.ibm.pc.hardware',
       'soc.religion.christian', 'comp.windows.x', 'rec.sport.baseball',
       'comp.graphics', 'sci.crypt', 'rec.motorcycles',
       'talk.politics.misc', 'rec.motorcycles', 'sci.med',
       'rec.sport.hockey', 'comp.graphics', 'sci.crypt',
       'sci.electronics', 'sci.space', 'rec.sport.hockey',
       'comp.os.ms-windows.misc', 'misc.forsale', 'talk.politics.misc',
       'sci.electronics', 'alt.atheism', 'talk.politics.misc',
       'alt.atheism', 'soc.religion.christian', 'rec.sport.hockey',
       'soc.religion.christian', 'comp.sys.ibm.pc.hardware',
       'comp.graphics', 'comp.os.ms-windows.misc', 'rec.sport.hockey',
       'sci.med', 'alt.atheism', 'rec.sport.hockey',
       'talk.politics.mideast', 'alt.atheism', 'talk.religion.misc',
       'misc.forsale', 'comp.sys.mac.hardware', 'sci.space',
       'comp.os.ms-windows.misc', 'rec.motorcycles', 'rec.motorcycles',
       'misc.forsale', 'sci.med', 'sci.med', 'alt.atheism',
       'comp.os.ms-windows.misc', 'talk.politics.mideast', 'alt.atheism',
       'rec.autos', 'comp.sys.ibm.pc.hardware', 'soc.religion.christian',
       'sci.space', 'talk.religion.misc', 'rec.sport.hockey',
       'comp.sys.ibm.pc.hardware', 'rec.sport.hockey',
       'talk.politics.mideast', 'talk.politics.misc',
       'comp.sys.ibm.pc.hardware', 'comp.os.ms-windows.misc',
       'alt.atheism', 'talk.politics.guns', 'sci.space', 'rec.autos',
       'talk.religion.misc', 'sci.crypt', 'talk.religion.misc',
       'rec.sport.baseball', 'alt.atheism', 'rec.sport.hockey',
       'sci.electronics', 'rec.sport.hockey', 'rec.sport.baseball',
       'rec.sport.hockey', 'comp.os.ms-windows.misc',
       'soc.religion.christian', 'soc.religion.christian',
       'talk.politics.misc', 'soc.religion.christian', 'alt.atheism',
       'talk.politics.misc', 'comp.graphics', 'sci.crypt',
       'rec.sport.baseball', 'comp.os.ms-windows.misc',
       'talk.religion.misc', 'misc.forsale', 'rec.autos', 'rec.autos',
       'sci.electronics', 'comp.windows.x', 'soc.religion.christian',
       'comp.os.ms-windows.misc', 'comp.sys.mac.hardware',
       'talk.politics.mideast', 'comp.sys.ibm.pc.hardware',
       'comp.graphics', 'sci.crypt', 'misc.forsale', 'sci.space',
       'rec.autos', 'alt.atheism', 'rec.motorcycles', 'rec.motorcycles',
       'talk.politics.guns', 'comp.sys.ibm.pc.hardware', 'alt.atheism',
       'soc.religion.christian', 'rec.sport.baseball', 'sci.crypt',
       'comp.sys.mac.hardware', 'sci.space', 'misc.forsale',
       'comp.graphics', 'rec.sport.hockey', 'talk.politics.mideast',
       'talk.politics.mideast', 'sci.med', 'sci.crypt', 'misc.forsale',
       'comp.sys.ibm.pc.hardware', 'rec.autos', 'misc.forsale',
       'misc.forsale', 'comp.sys.mac.hardware', 'talk.politics.mideast',
       'rec.motorcycles', 'sci.crypt', 'comp.os.ms-windows.misc',
       'soc.religion.christian', 'talk.politics.misc', 'alt.atheism',
       'talk.politics.misc', 'soc.religion.christian',
       'soc.religion.christian', 'comp.sys.mac.hardware', 'alt.atheism',
       'talk.politics.misc', 'sci.space', 'sci.space', 'rec.autos',
       'rec.autos', 'talk.politics.guns', 'sci.space', 'rec.autos',
       'rec.motorcycles', 'sci.space', 'rec.autos',
       'soc.religion.christian', 'talk.politics.mideast',
       'talk.politics.guns', 'talk.politics.mideast', 'rec.autos',
       'comp.os.ms-windows.misc', 'rec.sport.baseball', 'sci.electronics',
       'comp.sys.ibm.pc.hardware', 'comp.os.ms-windows.misc',
       'comp.sys.ibm.pc.hardware'], dtype='<U24')

In [35]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.655

In [36]:
classification_report(y_test,y_pred)

'                          precision    recall  f1-score   support\n\n             alt.atheism       0.59      0.89      0.71        18\n           comp.graphics       0.44      0.39      0.41        18\n comp.os.ms-windows.misc       0.68      0.86      0.76        22\ncomp.sys.ibm.pc.hardware       0.58      0.60      0.59        25\n   comp.sys.mac.hardware       0.69      0.43      0.53        21\n          comp.windows.x       1.00      0.20      0.33        25\n            misc.forsale       0.57      0.72      0.63        18\n               rec.autos       0.60      0.83      0.70        18\n         rec.motorcycles       0.55      0.75      0.63        16\n      rec.sport.baseball       0.76      0.72      0.74        18\n        rec.sport.hockey       0.56      0.93      0.70        15\n               sci.crypt       0.69      0.95      0.80        19\n         sci.electronics       0.38      0.38      0.38        16\n                 sci.med       0.76      0.76      0.76        17\n               sci.space       1.00      0.81      0.89        21\n  soc.religion.christian       0.96      1.00      0.98        23\n      talk.politics.guns       0.77      0.36      0.49        28\n   talk.politics.mideast       0.84      0.80      0.82        20\n      talk.politics.misc       0.50      0.78      0.61        18\n      talk.religion.misc       0.54      0.29      0.38        24\n\n                accuracy                           0.66       400\n               macro avg       0.67      0.67      0.64       400\n            weighted avg       0.69      0.66      0.64       400\n'